#!/usr/bin/env python3
import json
import argparse

# helper
def loadtext(fname):
    """load text from file, remove comments and blank
    """
    with open(fname, 'r') as f:
        rawtext = f.read().split('\n')
    # remove comment & blank
    cmt = '#'
    rst = list()
    for line in rawtext:
        line = line.split(cmt)[0].strip()
        if line:
            rst.append(line)
    return tuple(rst)


def parse_config_file(cfgfile):
    """parse config file to get data structure
    """
    text = loadtext('remlist.cfg')
    data = dict()
    N = len(text)
    index = 0
    while index < N:
        line = tuple(i.strip() for i in text[index].split())
        if line[0].startswith('$'):
            tag = line[0][1:].lower()
            data[tag] = dict()
            index += 1
            while True:
                line = tuple(i.strip() for i in text[index].split())
                if line[0].lower() == '$end':
                    index += 1
                    break
                else:
                    name = line[0].lower()
                    dtype = line[1]
                    dmodel = line[2]
                    assert dtype in datatyperange
                    assert dmodel in datamodelrange
                    data[tag][name] = {
                            "value" : None,
                            "datatype" : dtype,
                            "datamodel" : dmodel
                            }
                index += 1
    return data


def parse_infile(infile, data):
    """parse input file to get value

        param infile: input file
        param data: data skeleton from config file
    """
    text = loadtext(infile)
    N = len(text)
    index = 0
    while index < N:
        line = tuple(i.strip() for i in text[index].split())
        if line[0].startswith('$'):
            tag = line[0][1:].lower()
            nowdict = data[tag]
            index += 1
            while True:
                line = tuple(i.strip() for i in text[index].split())
                if line[0].lower() == '$end':
                    index += 1
                    break
                # block data
                elif line[0].startswith('@'):
                    name = line[0][1:].lower()
                    assert name in nowdict
                    index += 1
                    value = list()
                    while True:
                        line = tuple(i.strip() for i in text[index].split())
                        index += 1
                        if line[0].lower() == '@end':
                            break
                        value.append(line)
                # line data
                else:
                    name = line[0].lower()
                    assert name in nowdict
                    line = tuple(i.strip() for i in text[index].split())
                    value = line[1:]
                    index += 1

                nowdict[name]['value'] = value
    return data


def parsearg():
    """parse commandline arguments
    """
    parser = argparse.ArgumentParser()
    parser.add_argument('infile', type=str, help='input file name')
    parser.add_argument('--cfgfile', type=str, default='remlist.cfg', help='config file name')
    args = parser.parse_args()
    return args


datatyperange = ('b', 'i', 'd', 's', 'S')
datamodelrange = ('s', 'v', 'b')


if __name__ == '__main__':
    args = parsearg()
    dataframe = parse_config_file(args.cfgfile)
    rstdata = parse_infile(args.infile, dataframe)
    outfile = rstdata['rem']['jobname']['value'][0] + '_input.json'
    with open(outfile, 'w') as f:
        json.dump(rstdata, f, indent=4)
