#!/bin/bash

function infile() {
    cat > cross_G${1}.in << EOF
\$rem
    jobname     cross_G${1}
    dim         2
	hbar		1
    kT          1e-3
    Gamma0      0.${1}
\$end

\$grid
	rmin		-3			-12 	
	rmax		3			8
    boundary_rmin   -100    -11
    boundary_rmax   100     7
	Nr			9000        15000

	#-- fef related --#

	bandwidth	1.5
	derange		3e-6	3e-5
	gamma_cutoff 6e-4
\$end

\$simulation
    Ntraj       5000
    mass        14000		55000
    EndT        500000
    Nstep       2000000
    Anastep     10000
	Algorithms	CME BCME EF

	#-- init state relateda --#

    initTemp    5e-4
    vibstate    15
	elestate	0
    initmode    ring  	p_gaussian
	initravg	0	  	-10
	initpavg	0		${2}
\$end

\$surfaces
    surfnum     	2

    surfmode   harmonic fermi harmonic fermi
	@surfpara
		0.896 	0 		0					# i = 0, d = 0
		0.2 	0       0.67	0   		# i = 0, d = 1
		0.896 	0 		0.2					# i = 1, d = 0
	    0.2 	0    	-0.67  	-3.2   		# i = 1, d = 1
	@end

    gammamode	gaussian	gaussian
	@gammapara
		1		1		4		0
		1		0		0.5     -1.6
	@end
\$end
EOF
}

function subfile() {
    cat > sub.sh << EOF
#!/bin/bash
#PBS -N L('w')D
#PBS -l walltime=310:00:00
#PBS -l mem=120GB
#PBS -l nodes=1:ppn=48
cd \$PBS_O_WORKDIR
BIN=/data/home/Eplistical/code/ScatterProgram/install/bin
SCRATCHDIR=/scratch/Eplistical/\${PBS_JOBID}

mkdir -p \$SCRATCHDIR

if [ -f ".pbs.log" ]; then
	rm .pbs.log
fi

function runcmd() {
	# args: jobname, jobtype, nproc
	infile=\${1}.in
	base=\${1}.\${2}
	echo \${3}
	CMD=\`python3 \$BIN/scatter_gen_cmd.py --infile \${infile} --outdir \${SCRATCHDIR} --base=\${base} --jobtype \${2} --nproc \${3}\`
	echo \$CMD
	eval \$CMD
	mv \$SCRATCHDIR/* .
}


jobname=cross_G${G}
jobtype=simulation
nproc=\${PBS_NP}
#nproc=1
runcmd \${jobname} \${jobtype} \${nproc}

EOF
}

function subanalfile() {

cat > subanal.sh << EOF
#!/bin/bash
#PBS -N L('w')D
#PBS -l walltime=310:00:00
#PBS -l mem=20GB
#PBS -l nodes=1:ppn=1
cd \$PBS_O_WORKDIR
BIN=/data/home/Eplistical/code/ScatterProgram/install/bin
SCRATCHDIR=/scratch/Eplistical/\${PBS_JOBID}

mkdir -p \$SCRATCHDIR

if [ -f ".pbs.log" ]; then
	rm .pbs.log
fi

jobname=cross_G${G}
infile=\${jobname}.in

python3 \$BIN/checkfefdat.py \${infile} --savedir=\${SCRATCHDIR}

mkdir -p ctf
mv \${SCRATCHDIR}/* ./ctf/

EOF
}


CWD=`pwd`
Glist="01 03 05 08"
v=40

for G in ${Glist} ; do
    echo now on G${G}
    mkdir -p G${G}
    cd G${G}
    infile ${G} ${v}
    subfile ${G} ${v} ; TOSUB=sub.sh
    cp ${CWD}/init/cross_v${v}.init cross_G${G}.init
    #subanalfile ${G} ; TOSUB=subanal.sh
    if [ "$1" == "run" ];then
        qsub -o .pbs.out -j oe ${TOSUB}
        sleep 1
    fi
    cd $CWD
done
