#!/bin/bash

Vlist="20 30 40 50 60 70 80 90"
lastv=20

for v in ${Vlist}; do
    sed -i s/"initpavg\([\t ]\+\)0\([\t ]\+\)${lastv}"/"initpavg\10\2${v}"/ cross.in 
    bash ../../install/bin/scatter_exe.sh cross.in prepareinit
    mv cross.init ./init/cross_v${v}.init
    lastv=${v}
done
