#!/bin/bash

Vlist="20 40 60 80"
lastv=20

for v in ${Vlist}; do
    sed -i s/"initpavg\([\t ]\+\)0\([\t ]\+\)${lastv}"/"initpavg\10\2${v}"/ newns.in 
    bash ../../install/bin/scatter_exe.sh newns.in prepareinit
    mv newns.init ./init/newns_v${v}.init
    lastv=${v}
done
